services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  user-service:
    build: ./user-service
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://appuser:password@db:5432/appdb
      - JWT_SECRET=supersecretkey
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  todo-service:
    build: ./todo-service
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://appuser:password@db:5432/appdb
      - JWT_SECRET=supersecretkey
    ports:
      - "3002:3002"
    depends_on:
      db:
        condition: service_healthy
      user-service:
        condition: service_started
    restart: on-failure

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      user-service:
        condition: service_started
      todo-service:
        condition: service_started

volumes:
  app-db-data:
